# Generated by Django 4.2.19 on 2025-02-11 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('category', models.CharField(choices=[('Drum Kit', 'Drum Kit'), ('Presets', 'Presets'), ('Effects Rack', 'Effects Rack'), ('MIDI Rack', 'MIDI Rack'), ('Samples', 'Samples'), ('VST', 'VST'), ('Max4Live Patch', 'Max4Live Patch'), ('Max4Live Device', 'Max4Live Device')], max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('file_url', models.TextField()),
                ('image_url', models.TextField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
